name: Ubuntu

on:
  push:
    paths:
     - 'doc/**'
     - 'BPt/**'
  pull_request:

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest
        pip install .
    - name: Run py tests
      run: |
        pytest
    - name: Add extra and test
      run: |
        pip install .[extra]
        pytest
    - name: Run lower pandas version test
      run: |
        pip install pandas==1.1.5
        pytest
    
